@startuml workflow

left to right direction
skinparam ParticipantPadding 20
'skinparam linetype polyline

partition "Workflow" {
    (*) --> "StreamReceiver"
    "StreamReceiver" --> "Multiplexer"
    
    "Multiplexer" --> "MotionDetector"
    "Multiplexer" --> "HumanDetector"

    partition "debugMode" {
        "Multiplexer" .....> "Streamer"
        "MotionDetector" .....> "Streamer"
        "HumanDetector" .....> "Streamer"
    }

    "MotionDetector" --> "EventHandler"
    "HumanDetector" --> "EventHandler"

    "EventHandler" --> "AlertTrigger"
}

@enduml
