@startuml workflow

left to right direction
skinparam ParticipantPadding 20

partition "Workflow" {
    (*) --> "StreamReceiver"
    "StreamReceiver" --> "Multiplexer"
    
    "Multiplexer" --> "MotionDetector"
    "Multiplexer" --> "HumanDetector"

    "MotionDetector" --> "EventHandler"
    "HumanDetector" --> "EventHandler"

    "EventHandler" --> "AlertTrigger"

    partition "debugMode" {
        "Multiplexer" ..> "Streamer"
        "MotionDetector" ..> "Streamer"
        "HumanDetector" ..> "Streamer"
    }
}

@enduml